### ISSUE TITLE
Prettier config

### ISSUE THREAD

**Issue by alexpanchuk** [laststance/react-typescript-todo-example-2020#132]
Hi. First of all, thanks for this repo.
I noticed you use Prettier.
Could you add your prettier global settings to local file .prettierrc

**Comment by ryota-murakami** [comment]
@alexpanchuk I'm integrating prettier in ESLint,
therefore prettier config is stored at [.eslintrc](https://github.com/laststance/react-typescript-todo-example-2020/blob/8e7d569c25694839adf605cab6731ca025bb2253/.eslintrc#L21-L26).

But I guess put `.prettierrc` make better experience for many repo users, contributors who familiar with prettier.

I'm going to do this.

**Comment by alexpanchuk** [comment]
Hmm. I have Prettier and ESLint extensions for my VSCode, but it didn't catch prettier settings from .eslintrc.
Try to move settings to .prettierrc and it works.

**Comment by ryota-murakami** [comment]
Done with https://github.com/laststance/react-typescript-todo-example-2020/commit/4b0c8d6ec3f7dd0b5dc0299138a2496e5bca4816
